# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0654df9dafdb437aef9eb7eb2ed6e67d8a0d5f62239740389e8ad9e6a4b3ffad78b93f16adddbe1cbd24957bde05b0bce585c50f3a02c10a78e84f62b3b13e8d

test:
  secret_key_base: 6be894c512b80bc40273fb8de634503da137a5339a9fb597e70ce9de4379182f7c67b8e5f4cd4a5b9cc33f0a91c492b793f15b237f988ce8fbc109941b5267af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
